# Generated by Django 5.1.2 on 2024-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Poor"), (2, "Average"), (3, "Good"), (4, "Very Good"), (5, "Excellent")],
                db_index=True,
                default=5,
                verbose_name="Rating",
            ),
        ),
    ]
