# Generated by Django 5.1.2 on 2024-11-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productreview_unique_product_review_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
