# Generated by Django 5.1.2 on 2024-11-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_productreview_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productproperty",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_properties",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
