# Generated by Django 5.1.2 on 2024-11-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_productproperty_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdiscount",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="products.product",
                verbose_name="Product",
            ),
            preserve_default=False,
        ),
    ]
