# Generated by Django 5.1.2 on 2024-12-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_productreview_unique_product_review_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productwishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whish_list",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
