# Generated by Django 5.1.2 on 2024-12-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_product_category_productbrand_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbrand",
            name="title",
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Title"),
        ),
    ]
