# Generated by Django 5.1.2 on 2024-12-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_productbrand_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.productcategory",
                verbose_name="Parent",
            ),
        ),
    ]
