version: '3'
services:
  db:
    image: postgis/postgis:16-3.5
    restart: always
    volumes:
      - ./db_volume/data/:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=dev_pass
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=shop
    ports:
      - "7999:5432"

  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - 7164:6379

volumes:
  db_volume:
