# Generated by Django 5.0.2 on 2024-07-03 20:18

import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("title", models.CharField(max_length=50, verbose_name="title")),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                ("send_in_app", models.BooleanField(default=False, verbose_name="send in app")),
                ("send_notification", models.BooleanField(default=False, verbose_name="send notification")),
                ("send_email", models.BooleanField(default=False, verbose_name="send email")),
                ("send_sms", models.BooleanField(default=False, verbose_name="send sms")),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="messaging.group", verbose_name="group"),
                ),
            ],
            options={
                "verbose_name": "group message",
                "verbose_name_plural": "group messages",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("token", models.UUIDField(db_index=True, editable=False, unique=True, verbose_name="Token")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                ("send_in_app", models.BooleanField(default=False, verbose_name="send in app")),
                ("send_notification", models.BooleanField(default=False, verbose_name="send notification")),
                ("send_email", models.BooleanField(default=False, verbose_name="send email")),
                ("send_sms", models.BooleanField(default=False, verbose_name="send sms")),
                ("is_seen", models.BooleanField(default=False, verbose_name="is seen")),
                (
                    "event_type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Not Defined"), (2, "New Answer")],
                        db_index=True,
                        default=1,
                        editable=False,
                        verbose_name="Event Type",
                    ),
                ),
                ("event_data", models.TextField(blank=True, default="{}", editable=False, verbose_name="Event Data")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user"
                    ),
                ),
            ],
            options={
                "verbose_name": "user message",
                "verbose_name_plural": "user messages",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GroupUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="messaging.group", verbose_name="group"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user"
                    ),
                ),
            ],
            options={
                "verbose_name": "group user",
                "verbose_name_plural": "group users",
                "unique_together": {("group", "user")},
            },
        ),
    ]
