# Generated by Django 5.1.2 on 2024-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="groupuser",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="groupuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="usermessage",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="usermessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="groupuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At"),
        ),
    ]
