# Generated by Django 5.1.2 on 2024-11-30 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_alter_cartitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                validators=[django.core.validators.MinValueValidator(1, message="Minimum Quantity Of Product Is 1")],
                verbose_name="Quantity",
            ),
        ),
    ]
