# Generated by Django 5.1.2 on 2024-11-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_cartitem_quantity"),
        ("products", "0006_productdiscount_product"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"),
                name="unique_product_cart",
                violation_error_message="Duplicate Product Inside The Cart",
            ),
        ),
    ]
