from django.utils.translation import gettext_lazy as _

EXAMPLE_CHOICE_NOT_DEFINED = -1
EXAMPLE_CHOICE_ZERO = 0
EXAMPLE_CHOICE_ONE = 1
EXAMPLE_CHOICE = (
    (EXAMPLE_CHOICE_NOT_DEFINED, _("EXAMPLE CHOICE NOT DEFINED")),
    (EXAMPLE_CHOICE_ZERO, _("EXAMPLE CHOICE ZERO")),
    (EXAMPLE_CHOICE_ONE, _("EXAMPLE CHOICE ONE")),
)


MESSAGE_EVENT_NOT_DEFINED = 1
MESSAGE_EVENT_NEW_ANSWER = 2
MESSAGE_EVENTS = (
    (MESSAGE_EVENT_NOT_DEFINED, _("Not Defined")),
    (MESSAGE_EVENT_NEW_ANSWER, _("New Answer")),
)

COUPON_TYPE_PERCENT = 0
COUPON_TYPE_AMOUNT = 1
COUPON_TYPES = (
    (COUPON_TYPE_PERCENT, _("Percent")),
    (COUPON_TYPE_AMOUNT, _("Amount")),
)


DISCOUNT_TYPE_PERCENT = 0
DISCOUNT_TYPE_AMOUNT = 1
DISCOUNT_TYPES = (
    (DISCOUNT_TYPE_PERCENT, _("Percent")),
    (DISCOUNT_TYPE_AMOUNT, _("Amount")),
)


RATING_POOR = 1
RATING_AVERAGE = 2
RATING_GOOD = 3
RATING_VERY_GOOD = 4
RATING_EXCELLENT = 5
RATINGS = (
    (RATING_POOR, _("Poor")),
    (RATING_AVERAGE, _("Average")),
    (RATING_GOOD, _("Good")),
    (RATING_VERY_GOOD, _("Very Good")),
    (RATING_EXCELLENT, _("Excellent")),
)


HOLDER_MAIN_PAGE_FIRST = 0
HOLDER_MAIN_PAGE_SECOND = 1
HOLDERS = (
    (HOLDER_MAIN_PAGE_FIRST, _("Main Page - First")),
    (HOLDER_MAIN_PAGE_SECOND, _("Main Page - Second")),
)


SHIPMENT_SERVICE_TYPE_MANUAL = 0
SHIPMENT_SERVICE_TYPES = (
    (
        SHIPMENT_SERVICE_TYPE_MANUAL,
        _("Manual"),
    ),
)


ORDER_STATUS_PAYMENT_WAITING = 0
ORDER_STATUS_ORDER_PLACED = 1
ORDER_STATUS_PRODUCT_PACKAGING = 2
ORDER_STATUS_READY_FOR_SHIPMENT = 3
ORDER_STATUS_ON_THE_WAY = 4
ORDER_STATUS_DROPPED_IN_DELIVERY = 5
ORDER_STATUS_DELIVERED = 6
ORDER_STATUS_CANCELED = 7
ORDER_STATUSES = (
    (ORDER_STATUS_PAYMENT_WAITING, _("Payment waiting")),
    (ORDER_STATUS_ORDER_PLACED, _("Order placed")),
    (ORDER_STATUS_PRODUCT_PACKAGING, _("Product packaging")),
    (ORDER_STATUS_READY_FOR_SHIPMENT, _("Ready for shipment")),
    (ORDER_STATUS_ON_THE_WAY, _("On the way")),
    (ORDER_STATUS_DROPPED_IN_DELIVERY, _("Dropped in the delivery station")),
    (ORDER_STATUS_DELIVERED, _("Delivered")),
    (ORDER_STATUS_CANCELED, _("Canceled")),
)


SORT_NEWEST = "1"
SORT_MOST_VIEWED = "2"

SORT_CHOICES = (
    (SORT_NEWEST, _("Newest")),
    (SORT_MOST_VIEWED, _("Most Viewed")),
)
