# Generated by Django 5.1.2 on 2024-11-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponconsume",
            name="coupon",
            field=models.ForeignKey(
                help_text="The coupon that was consumed.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumptions",
                to="promotions.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="couponconsume",
            name="user",
            field=models.ForeignKey(
                help_text="The user who used the coupon.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coupon_consumptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
