# Generated by Django 5.1.2 on 2024-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0002_alter_couponconsume_coupon_alter_couponconsume_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Percent"), (1, "Amount")],
                db_index=True,
                help_text="Type of discount: percentage or fixed amount.",
                verbose_name="Discount Type",
            ),
        ),
    ]
