# Generated by Django 5.1.2 on 2024-12-05 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0003_alter_coupon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="amount",
            field=models.FloatField(
                blank=True,
                help_text="The actual discount amount applied to the cart (fixed or percentage).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Discount Amount",
            ),
        ),
    ]
