# Generated by Django 5.1.2 on 2024-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="read_time",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Estimated time to read the post in minutes. Calculated based on word count.",
                verbose_name="Read Time (minutes)",
            ),
        ),
    ]
