# Generated by Django 5.1.2 on 2024-11-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_price",
            field=models.FloatField(verbose_name="Product Price"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_title",
            field=models.CharField(max_length=100, verbose_name="Product Title"),
        ),
    ]
