# Generated by Django 5.1.2 on 2024-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_orderitem_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordershipment",
            name="shipment_price",
            field=models.FloatField(verbose_name="Shipment Price"),
        ),
    ]
