# Generated by Django 5.1.2 on 2024-11-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_ordershipment_shipment_price"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordershipment",
            name="shipment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="shipments.shipmenttype", verbose_name="Shipment Type"
            ),
        ),
    ]
