# Generated by Django 5.1.2 on 2024-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_ordershipment_shipment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon_total_discount",
            field=models.FloatField(
                help_text="Total discount applied via coupon. This is the discount from a coupon applied to the order.",
                verbose_name="Coupon Discount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_total_discount",
            field=models.FloatField(
                help_text="Total discount applied directly to the products. This does not include coupon discounts.",
                verbose_name="Product Discount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_total_price",
            field=models.FloatField(
                help_text="The total price of all products before any discounts.", verbose_name="Total Product Price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(
                help_text="The final total price after all discounts (both product and coupon discounts) have been applied.",
                verbose_name="Total Price",
            ),
        ),
    ]
