# Generated by Django 5.1.2 on 2024-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_shipment_price_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="current_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Payment waiting"),
                    (1, "Order placed"),
                    (2, "Product packaging"),
                    (3, "Ready for shipment"),
                    (4, "On the way"),
                    (5, "Dropped in the delivery station"),
                    (6, "Delivered"),
                    (7, "Canceled"),
                ],
                default=1,
                help_text="The Current Order Status",
                verbose_name="Current Order Status",
            ),
        ),
    ]
