# Generated by Django 5.1.2 on 2024-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_order_current_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatus",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Timestamp"),
        ),
    ]
