# Generated by Django 5.0.2 on 2024-07-03 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_is_verified_phone_number_user_phone_number"),
    ]

    operations = []
