# Generated by Django 5.0.2 on 2024-02-22 11:29

import environ
from django.contrib.auth.hashers import make_password
from django.db import migrations

env = environ.Env()
USERNAME = env("DEFAULT_USER_USERNAME", default="admin")
PASSWORD = env("DEFAULT_USER_PASSWORD", default="admin")


def forwards_func(apps, schema_editor):
    User = apps.get_model("account", "User")
    db_alias = schema_editor.connection.alias

    user = User.objects.using(db_alias).create(username=USERNAME, first_name="Admin")

    user.password = make_password(PASSWORD)
    user.is_superuser = True
    user.is_staff = True
    user.save()


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    User = apps.get_model("account", "User")
    db_alias = schema_editor.connection.alias

    user = User.objects.using(db_alias).filter(username=USERNAME)

    user.delete()


class Migration(migrations.Migration):
    dependencies = [("account", "0003_remove_user_username")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
