# Generated by Django 5.0.2 on 2024-07-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_create_default_user"),
        ("wallet", "__first__"),
    ]
    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="wallet.wallet",
                verbose_name="Wallet",
            ),
        ),
    ]
