# Generated by Django 5.1.2 on 2024-11-11 09:35

from django.db import migrations

import apps.account.managers


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_newuserproxy_options_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.account.managers.UserManager()),
            ],
        ),
    ]
