# Generated by Django 5.1.2 on 2024-11-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="title",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Title"),
        ),
    ]
