# Generated by Django 5.1.2 on 2024-12-10 19:11

import django.core.validators
import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0002_alter_city_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the inquiry category (e.g., Buying Support).",
                        max_length=100,
                        unique=True,
                        verbose_name="title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Category",
                "verbose_name_plural": "Inquiry Categories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the person submitting the inquiry.", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address of the person submitting the inquiry.",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                ("subject", models.CharField(help_text="The subject of the inquiry.", max_length=150, verbose_name="Subject")),
                (
                    "message",
                    models.TextField(
                        help_text="The detailed message from the person submitting the inquiry.",
                        validators=[django.core.validators.MaxLengthValidator(500)],
                        verbose_name="Message",
                    ),
                ),
                (
                    "relevant_url",
                    models.URLField(
                        blank=True,
                        help_text="An optional URL relevant to your inquiry (e.g., a related webpage).",
                        null=True,
                        verbose_name="Relevant URL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select the category of the inquiry.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="info.inquirycategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Us Inquiry",
                "verbose_name_plural": "Contact Us Inquiries",
                "ordering": ["-created_at"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
