# Generated by Django 5.1.2 on 2024-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0003_inquirycategory_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirycategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At"),
        ),
        migrations.AddField(
            model_name="inquirycategory",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="inquirycategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
    ]
