# Generated by Django 5.1.2 on 2024-12-10 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0004_inquirycategory_created_at_inquirycategory_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirycategory",
            name="priority",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Priority of the record. Starting from 0",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Priority",
            ),
        ),
    ]
