# Generated by Django 5.1.2 on 2024-12-11 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0005_inquirycategory_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquirycategory",
            options={
                "ordering": ["-priority"],
                "verbose_name": "Inquiry Category",
                "verbose_name_plural": "Inquiry Categories",
            },
        ),
    ]
