# Generated by Django 5.1.2 on 2024-11-21 14:07

import django.core.validators
import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "service_type",
                    models.IntegerField(
                        choices=[(0, "Manual")],
                        help_text="Select the type of service for this shipment.",
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A detailed description of the shipment type.",
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                        verbose_name="Description",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Upload the logo for the shipment type.",
                        upload_to="shipment_type_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("price", models.IntegerField(help_text="The base price for this shipment type.", verbose_name="Price")),
                (
                    "vat",
                    models.FloatField(
                        help_text="The VAT (Value Added Tax) percentage for this shipment type.", verbose_name="VAT"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Type",
                "verbose_name_plural": "Shipment Types",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
