# Generated by Django 5.1.2 on 2024-12-02 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmenttype",
            name="vat",
            field=models.FloatField(
                help_text="The VAT (Value Added Tax) percentage for this shipment type.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="VAT",
            ),
        ),
    ]
