# Generated by Django 5.1.2 on 2024-11-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
        ("products", "0006_productdiscount_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productofferitem",
            name="sold_stock",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Sold Stock"),
        ),
        migrations.AlterField(
            model_name="productofferitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
