# Generated by Django 5.1.2 on 2025-01-04 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_productofferitem_sold_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productofferitem",
            name="discount",
            field=models.FloatField(
                db_index=True,
                help_text="Percent",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Discount",
            ),
        ),
    ]
